if(NOT TARGET tiff)
    set(LIBNAME tiff-4.4.0)
    set(ALL_LIB_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty)
    set(ALL_LIB_BIN_DIR ${CMAKE_BINARY_DIR}/thirdparty)
    set(${LIBNAME}_SRC_DIR ${ALL_LIB_SRC_DIR}/${LIBNAME})
    set(${LIBNAME}_BIN_DIR ${ALL_LIB_BIN_DIR}/${LIBNAME})
    message("${LIBNAME}_SRC_DIR:${${LIBNAME}_SRC_DIR}")
    message("${LIBNAME}_BIN_DIR:${${LIBNAME}_BIN_DIR}")
    if(CMAKE_SYSTEM_NAME MATCHES "Linux")
        add_compile_definitions(DYZ)
    endif()
    add_subdirectory(${${LIBNAME}_SRC_DIR}/)
endif()

set(TIFF_ROOT_DIR     ${${LIBNAME}_SRC_DIR})
set(TIFF_INCLUDE_DIRS ${TIFF_ROOT_DIR}     ${TIFF_ROOT_DIR}/include)
set(TIFF_LIBRARY_DIRS ${TIFF_ROOT_DIR}     ${TIFF_ROOT_DIR}/lib    )

include_directories(${TIFF_INCLUDE_DIRS}   ${${LIBNAME}_BIN_DIR}/     ${${LIBNAME}_BIN_DIR}/include)
link_directories   (${TIFF_LIBRARY_DIRS}   ${${LIBNAME}_BIN_DIR}/     ${${LIBNAME}_BIN_DIR}/lib)

set(TIFF_LIBRARY   $<TARGET_OBJECTS:tiff>)
set(TIFF_LIBRARIES $<TARGET_OBJECTS:tiff>)
