if(NOT TARGET freetype)
    set(LIBNAME freetype-2.12.1)
    set(ALL_LIB_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/../thirdparty)
    set(ALL_LIB_BIN_DIR ${CMAKE_BINARY_DIR}/thirdparty)
    set(${LIBNAME}_SRC_DIR ${ALL_LIB_SRC_DIR}/${LIBNAME})
    set(${LIBNAME}_BIN_DIR ${ALL_LIB_BIN_DIR}/${LIBNAME})
    message("${LIBNAME}_SRC_DIR:${${LIBNAME}_SRC_DIR}")
    message("${LIBNAME}_BIN_DIR:${${LIBNAME}_BIN_DIR}")
    if(CMAKE_SYSTEM_NAME MATCHES "Linux")
        add_compile_definitions(DYZ)
    endif()
    add_subdirectory(${${LIBNAME}_SRC_DIR}/)
endif()

set(FREETYPE_ROOT_DIR     ${${LIBNAME}_SRC_DIR})
set(FREETYPE_INCLUDE_DIRS ${FREETYPE_ROOT_DIR} ${FREETYPE_ROOT_DIR}/include)
set(FREETYPE_LIBRARY_DIRS ${FREETYPE_ROOT_DIR} ${FREETYPE_ROOT_DIR}/lib    )

include_directories(${FREETYPE_INCLUDE_DIRS}   ${${LIBNAME}_BIN_DIR}/     ${${LIBNAME}_BIN_DIR}/include)
link_directories   (${FREETYPE_LIBRARY_DIRS}   ${${LIBNAME}_BIN_DIR}/     ${${LIBNAME}_BIN_DIR}/lib)

set(FREETYPE_LIBRARY   $<TARGET_OBJECTS:freetype>)
set(FREETYPE_LIBRARIES $<TARGET_OBJECTS:freetype>)
